# Generated by Django 5.0.6 on 2024-07-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='invisible', max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
