# Generated by Django 5.0.6 on 2024-07-16 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmed', '0004_remove_profile_follows_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Your bio here', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='profileBanner',
            field=models.ImageField(default='C:\\Users\\Anish\\Downloads\\arthurpfp.jpeg', upload_to='socialmed/files/profilebanners'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default='C:\\Users\\Anish\\Downloads\\samurai.jpg', upload_to='socialmed/files/profilepics'),
        ),
        migrations.CreateModel(
            name='UserPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
