# Generated by Django 5.0.6 on 2024-07-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmed', '0005_profile_bio_profile_profilebanner_profile_profilepic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposts',
            name='community',
            field=models.CharField(default='DayzOutGang', max_length=32),
        ),
        migrations.AddField(
            model_name='userposts',
            name='image',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='userposts',
            name='nsfw',
            field=models.BooleanField(default=False),
        ),
    ]
