# Generated by Django 5.0.6 on 2024-07-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmed', '0006_userposts_community_userposts_image_userposts_nsfw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='image',
            field=models.FileField(default=None, upload_to='socialmed/files/postpics'),
        ),
    ]
