# Generated by Django 5.0.6 on 2024-07-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmed', '0008_userposts_dislikes_userposts_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposts',
            name='title',
            field=models.CharField(default='DayzOutTitle', max_length=50),
        ),
    ]
