# Generated by Django 5.0.6 on 2024-07-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmed', '0009_userposts_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposts',
            name='imgorvid',
            field=models.IntegerField(choices=[(0, 'NoFile'), (1, 'Image'), (2, 'Video')], default=0),
        ),
        migrations.AlterField(
            model_name='userposts',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='socialmed/files/postpics'),
        ),
    ]
