# Generated by Django 5.0.6 on 2024-07-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmed', '0010_userposts_imgorvid_alter_userposts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='socialmed/files/postpics'),
        ),
    ]
