# Generated by Django 5.0.6 on 2024-07-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmed', '0011_alter_userposts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileBanner',
            field=models.ImageField(default='default/arthurpfp.jpeg', upload_to='socialmed/files/profilebanners'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default='default/samurai.jpg', upload_to='socialmed/files/profilepics'),
        ),
        migrations.AlterField(
            model_name='userposts',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='postpics/'),
        ),
    ]
