# Generated by Django 5.0.6 on 2024-07-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmed', '0012_alter_profile_profilebanner_alter_profile_profilepic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='image',
            field=models.FileField(blank=True, default=None, upload_to='postpics/'),
        ),
    ]
