# Generated by Django 5.0.6 on 2024-07-27 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmed', '0013_alter_userposts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileBanner',
            field=models.ImageField(default='default/arthurpfp.jpeg', upload_to='profilebanners/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default='default/samurai.jpg', upload_to='profilepics/'),
        ),
        migrations.CreateModel(
            name='FriendRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='socialmed.profile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='socialmed.profile')),
            ],
        ),
    ]
