# Generated by Django 5.0.6 on 2024-07-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmed', '0016_alter_userposts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='image',
            field=models.FileField(blank=True, default='default/arthurpfp.jpeg', upload_to='postpics/'),
        ),
    ]
