# Generated by Django 5.0.6 on 2024-07-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmed', '0017_alter_userposts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileBanner',
            field=models.ImageField(default=None, upload_to='profilebanners/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default=None, upload_to='profilepics/'),
        ),
        migrations.AlterField(
            model_name='userposts',
            name='image',
            field=models.FileField(blank=True, default=None, upload_to='postpics/'),
        ),
    ]
