# Generated by Django 5.0.6 on 2024-07-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmed', '0018_alter_profile_profilebanner_alter_profile_profilepic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileBanner',
            field=models.ImageField(blank=True, default='default/arthurpfp.jpeg', upload_to='profilebanners/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(blank=True, default='default/samurai.jpg', upload_to='profilepics/'),
        ),
    ]
