# Generated by Django 5.0.6 on 2024-07-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmed', '0019_alter_profile_profilebanner_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileBanner',
            field=models.ImageField(blank=True, default='profilebanners/arthurpfp.jpeg', upload_to='profilebanners/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(blank=True, default='profilepics/samurai.jpg', upload_to='profilepics/'),
        ),
    ]
