# Generated by Django 5.0.6 on 2024-08-11 08:41

import socialmed.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmed', '0020_alter_profile_profilebanner_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', socialmed.models.CaseInsensitiveUserManager()),
            ],
        ),
    ]
